# Generated by Django 4.2.2 on 2024-05-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employeeid', models.CharField(max_length=30)),
                ('logintime', models.DateTimeField(null=True)),
                ('logofftime', models.DateTimeField(null=True)),
                ('totalbreakTimex', models.CharField(max_length=100)),
                ('totalmeetingTimex', models.CharField(max_length=100)),
                ('totaldownTimex', models.CharField(max_length=100)),
                ('totalworkx', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=30)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employeeid', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=40)),
                ('login', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employeeid', models.CharField(max_length=30)),
                ('leaveType', models.CharField(choices=[('Half Day', 'Half Day'), ('Full Day', 'Full Day')], max_length=10)),
                ('halfDayDate', models.DateField(blank=True, null=True)),
                ('fromdate', models.DateField(blank=True, null=True)),
                ('todate', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('applieddate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employeeid', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=30)),
                ('productivity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appreciations', models.IntegerField()),
                ('extraInitiatives', models.IntegerField()),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achievement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('newClient', models.CharField(max_length=50)),
                ('renewals', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PublicholidaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employeeid', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=30)),
                ('dateofbirth', models.CharField(max_length=30)),
                ('joiningdate', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='attendance_app/static')),
                ('accountnumber', models.CharField(max_length=30)),
                ('bankname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=30)),
                ('ifsccode', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('logintime', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
                ('department', models.CharField(max_length=30)),
                ('shifttime', models.CharField(max_length=30)),
                ('idproof', models.FileField(upload_to='attendance_app/static')),
                ('educationalcertificate', models.FileField(upload_to='attendance_app/static')),
                ('workexperience', models.FileField(upload_to='attendance_app/static')),
                ('resume', models.FileField(upload_to='attendance_app/static')),
                ('others', models.FileField(upload_to='attendance_app/static')),
                ('maritalstatus', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalarySlipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employeeid', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('totalPayableDays', models.DecimalField(decimal_places=1, max_digits=10)),
                ('totalleave', models.DecimalField(decimal_places=1, max_digits=10)),
                ('paidleave', models.DecimalField(decimal_places=1, max_digits=10)),
                ('Latelogin', models.DecimalField(decimal_places=1, max_digits=10)),
                ('salarydeductedleave', models.DecimalField(decimal_places=1, max_digits=10)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('perdaysalary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('deductionamount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('incentive', models.DecimalField(decimal_places=3, max_digits=10)),
                ('leaveencashment', models.DecimalField(decimal_places=3, max_digits=10)),
                ('monthlysalary', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeekoffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employeeid', models.CharField(max_length=30)),
                ('weekoff1', models.DateField(blank=True, null=True)),
                ('weekoff2', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
