# Generated by Django 4.2.2 on 2024-03-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_rename_totalworkingdays_salaryslipmodel_totalpayabledays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryslipmodel',
            old_name='totalpayabledays',
            new_name='totalPayableDays',
        ),
    ]
