# Generated by Django 4.2.2 on 2024-01-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_regmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='noofdays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
