# Generated by Django 4.2.2 on 2024-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_salaryslipmodel_incentive_salaryslipmodel_paidleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='incentive',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
