# Generated by Django 4.2.2 on 2024-01-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_leavemodel_noofdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemodel',
            name='noofdays',
        ),
    ]
