# Generated by Django 4.2.2 on 2024-05-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_commentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='employee_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
