# Generated by Django 4.2.2 on 2024-03-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_alter_salaryslipmodel_incentive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='paidleave',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='salarydeductedleave',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='totalPayableDays',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='totalleave',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
