# Generated by Django 4.2.2 on 2024-03-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_alter_salaryslipmodel_paidleave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryslipmodel',
            name='totalleave',
        ),
    ]
