# Generated by Django 4.2.2 on 2024-01-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_remove_leavemodel_noofdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='num_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
