# Generated by Django 4.2.2 on 2024-05-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_commentsmodel_employee_id_commentsmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsmodel',
            old_name='employee_id',
            new_name='employeeid',
        ),
    ]
