# Generated by Django 4.2.2 on 2024-03-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_remove_salaryslipmodel_totalleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslipmodel',
            name='totalleave',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
