# Generated by Django 4.2.2 on 2024-01-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_leavemodel_num_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemodel',
            name='num_days',
        ),
    ]
