# Generated by Django 4.2.2 on 2024-05-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_rename_employee_id_commentsmodel_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='created_at',
        ),
    ]
