# Generated by Django 4.2.2 on 2024-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_salaryslipmodel_totalleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='month',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
