# Generated by Django 4.2.2 on 2024-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_remove_commentsmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='extramodel',
            name='comments',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
