# Generated by Django 4.2.2 on 2024-06-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0007_extramodel_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extramodel',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
