# Generated by Django 4.2.2 on 2024-03-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0008_alter_salaryslipmodel_paidleave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='deductionamount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='incentive',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='monthlysalary',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='perdaysalary',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='salary',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
