# Generated by Django 4.2.2 on 2024-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0008_alter_extramodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslipmodel',
            name='byod',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
