# Generated by Django 4.2.2 on 2024-01-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0009_alter_leavemodel_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicholidaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('day', models.CharField(max_length=40)),
            ],
        ),
    ]
