# Generated by Django 4.2.2 on 2024-03-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0009_alter_salaryslipmodel_deductionamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extramodel',
            name='login',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
