# Generated by Django 4.2.2 on 2024-01-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0010_publicholidaysmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='applieddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
