# Generated by Django 4.2.2 on 2024-06-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0010_remove_salaryslipmodel_byod'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel',
            name='logintime_sat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
