# Generated by Django 4.2.2 on 2024-06-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0011_regmodel_logintime_sat'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslipmodel',
            name='byod',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
