# Generated by Django 4.2.2 on 2024-01-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0012_monthlydaterange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyDateRange',
        ),
    ]
