# Generated by Django 4.2.2 on 2024-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0012_salaryslipmodel_byod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='byod',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='incentive',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslipmodel',
            name='leaveencashment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
