# Generated by Django 4.2.2 on 2024-01-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0013_delete_monthlydaterange'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
