# Generated by Django 4.2.2 on 2024-01-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0014_attendancemodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicholidaysmodel',
            old_name='day',
            new_name='status',
        ),
    ]
