# Generated by Django 4.2.2 on 2024-01-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0015_rename_day_publicholidaysmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employeeid', models.IntegerField(unique=True)),
                ('designation', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('phonenumber', models.IntegerField()),
                ('dateofbirth', models.CharField(max_length=30)),
                ('joiningdate', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='attendance_app/static')),
                ('accountnumber', models.IntegerField()),
                ('bankname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=30)),
                ('ifsccode', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('leaveType', models.CharField(choices=[('Half Day', 'Half Day'), ('Full Day', 'Full Day')], max_length=10)),
                ('halfDayDate', models.DateField(blank=True, null=True)),
                ('fromdate', models.DateField(blank=True, null=True)),
                ('todate', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('leave_status', models.CharField(default='Pending', max_length=10)),
                ('days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('applieddate', models.DateField(blank=True, null=True)),
                ('logintime', models.DateTimeField(null=True)),
                ('logofftime', models.DateTimeField(null=True)),
                ('totalbreakTimex', models.CharField(max_length=100)),
                ('totalmeetingTimex', models.CharField(max_length=100)),
                ('totaldownTimex', models.CharField(max_length=100)),
                ('totalworkx', models.CharField(max_length=100, null=True)),
                ('attendance_status', models.CharField(max_length=30)),
                ('attendance_created', models.DateTimeField()),
                ('weekoff1', models.DateField(blank=True, null=True)),
                ('weekoff2', models.DateField(blank=True, null=True)),
                ('public_holiday_date', models.DateField(blank=True, null=True)),
                ('public_holiday_status', models.CharField(max_length=40)),
            ],
        ),
    ]
