# Generated by Django 4.2.2 on 2024-04-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0015_alter_regmodel_ifsccode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employeeid', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=30)),
                ('productivity', models.IntegerField(max_length=30)),
                ('quality', models.IntegerField(max_length=30)),
                ('appreciations', models.IntegerField(max_length=30)),
                ('extraInitiatives', models.IntegerField(max_length=30)),
                ('target', models.IntegerField(max_length=30)),
                ('achievement', models.IntegerField(max_length=30)),
                ('percentage', models.IntegerField(max_length=30)),
                ('newClient', models.IntegerField(max_length=30)),
                ('renewals', models.IntegerField(max_length=30)),
            ],
        ),
    ]
