# Generated by Django 4.2.2 on 2024-04-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0016_productivitymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivitymodel',
            name='achievement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='appreciations',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='extraInitiatives',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='newClient',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='productivity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='quality',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='renewals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='target',
            field=models.IntegerField(),
        ),
    ]
