# Generated by Django 4.2.2 on 2024-01-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0016_employeemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeModel',
        ),
    ]
