# Generated by Django 4.2.2 on 2024-04-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0017_alter_productivitymodel_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivitymodel',
            name='achievement',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='productivity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='quality',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='renewals',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productivitymodel',
            name='target',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
