# Generated by Django 4.2.2 on 2024-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0018_alter_productivitymodel_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivitymodel',
            name='newClient',
            field=models.CharField(max_length=50),
        ),
    ]
