# Generated by Django 4.2.2 on 2024-01-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0018_extramodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemodel',
            name='days',
        ),
    ]
