# Generated by Django 4.2.2 on 2024-01-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0019_remove_leavemodel_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
