# Generated by Django 4.2.2 on 2024-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0020_leavemodel_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySlipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('total_working_days', models.IntegerField()),
                ('salary_deducted_leave', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
