# Generated by Django 4.2.2 on 2024-02-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0022_rename_deduction_amount_salaryslipmodel_deductionamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryslipmodel',
            old_name='salarydeducted_leave',
            new_name='salarydeductedleave',
        ),
    ]
