# Generated by Django 4.2.2 on 2024-02-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0023_rename_salarydeducted_leave_salaryslipmodel_salarydeductedleave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalarySlipModel',
        ),
    ]
