# Generated by Django 4.2.2 on 2024-02-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0025_salaryslip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalarySlip',
        ),
    ]
