# Generated by Django 4.2.2 on 2024-02-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0027_salaryslipmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalarySlipModel',
        ),
    ]
