# Generated by Django 4.2.2 on 2024-02-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0029_salaryslipmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel',
            name='checkin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regmodel',
            name='checkout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
