# Generated by Django 4.2.2 on 2024-02-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0032_regmodel_checkin_regmodel_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmodel',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='regmodel',
            name='checkout',
        ),
    ]
